# 2017 May 26
# https://docpad.org/docs/deploy
# https://github.com/balupton/awesome-travis
language: node_js
node_js:
- "7"     # stable
cache:
  directories:
  - $HOME/.npm  # npm's cache
  - $HOME/.yarn-cache  # yarn's cache
before_script:
- npm run our:verify
after_success:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-publish.bash)"
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/travis-another.bash)"
notifications:
  slack:
    secure: cf67rWouYp7AcGhzxIQGuSdfza86RdT+e17PAsLvkXXEhryRLHDdzpdEo2Vd5/Jyu/uWERWgB+pzV5+ANOhvndyb671O4c8W7F+xlVPiUCSvzRCs5+oBQSvGIT8JJ2D1jnrHRqIUgUNbHKF1YL/G38fcNYIrOPQda9QoWXSZIYw=
  email:
    recipients:
      secure: BroaB+JmlJqMUzN0inJYiyicsUsy9/riC0zohE6TMgEbU9Tb0hVZqQ9I2mIOrPSAkQwy5QUNIcUjCODDzk/ZmTn0Tt4gQk10nbszC2v54KEd994SYZIq8ggY5aMnn2kXV6IYbVuUPJK2UAo2W29a7zehxJhgqGUdht49FzHvHzg=
