# This is a custom TRAVIS.yml file
# Do not update it with the base file automatically

# Use the latest travis infrastructure
sudo: false

# We use node
language: node_js
node_js:
  - "6"  # lts
cache:
  directories:
    - node_modules

# Deployment should be easier, but https://github.com/travis-ci/travis.rb/issues/315 is a thing
# Doesn't use --debug on `travis login` as that will output our github token
after_success: >
  if [ ! -z $GITHUB_TRAVIS_TOKEN ]; then
    echo "Deploying...";
    rvm install 2.1;
    gem install travis curb --no-rdoc --no-ri;
    travis login --skip-completion-check --org --github-token "$GITHUB_TRAVIS_TOKEN";
    export TRAVIS_ACCESS_TOKEN=`cat ~/.travis/config.yml | grep access_token | sed 's/ *access_token: *//'`;
    travis restart --debug --skip-completion-check --org -r "$DEPLOY_REPO_SLUG" -t "$TRAVIS_ACCESS_TOKEN";
    echo "Deployed";
  else
    echo "Skipped deploy";
  fi

# Custom deployment
# travis encrypt "GITHUB_TRAVIS_TOKEN=$GITHUB_TRAVIS_TOKEN" --add env.global
env:
  global:
    - DEPLOY_REPO_SLUG='bevry/staticsitegenerators-website'  # this is the repo owner and repo name that you want tested and deployed, set correctly
    - secure: WPW25SQXgwoW2nTu492+bIEflMarGnZZ20DuLmiUK8Ebnmh2GzJbz0aclfC38NR8+oJFaXk7HpXBTTdtXWjc8S1tvrm0yQqUahSOT/Hybewm1FqP1wIOYStSnsGfQMODSXOWFMX+fjKlHPe+lV1WeXzGh5tnudTEtNV5kzXXjOo=

# Custom notifications
notifications:
  slack:
    secure: cf67rWouYp7AcGhzxIQGuSdfza86RdT+e17PAsLvkXXEhryRLHDdzpdEo2Vd5/Jyu/uWERWgB+pzV5+ANOhvndyb671O4c8W7F+xlVPiUCSvzRCs5+oBQSvGIT8JJ2D1jnrHRqIUgUNbHKF1YL/G38fcNYIrOPQda9QoWXSZIYw=
  email:
    recipients:
      secure: BroaB+JmlJqMUzN0inJYiyicsUsy9/riC0zohE6TMgEbU9Tb0hVZqQ9I2mIOrPSAkQwy5QUNIcUjCODDzk/ZmTn0Tt4gQk10nbszC2v54KEd994SYZIq8ggY5aMnn2kXV6IYbVuUPJK2UAo2W29a7zehxJhgqGUdht49FzHvHzg=
